#Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-storage
  labels:
    app.kubernetes.io/name: ssbd06-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ssbd06-db
  labels:
    app.kubernetes.io/name: ssbd06-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ssbd06-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ssbd06-db
    spec:
      imagePullSecrets:
        - name: matino-registry
      containers:
        - name: ssbd06-db
          image: matino1/ssbd06:db-02
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: db-storage
---
#Autoscaler
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: waterly-auto-scaler
  namespace: waterly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: horizontalPodAutoscaler
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: ssbd06-db
spec:
  ports:
    - port: 3306
  selector:
    app.kubernetes.io/name: ssbd06-db
  clusterIP: None