CREATE USER ssbd06admin@'%' IDENTIFIED BY '12345';
CREATE USER ssbd06auth@'%' IDENTIFIED BY '12345';
CREATE USER ssbd06mok@'%' IDENTIFIED BY '12345';
CREATE USER ssbd06mol@'%' IDENTIFIED BY '12345';

# CREATE DATABASE ssbd06;

USE ssbd06;

GRANT ALL PRIVILEGES ON ssbd06.* TO 'admin'@'%' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON ssbd06.* TO 'ssbd06admin'@'%' WITH GRANT OPTION;

GRANT SELECT ON ssbd06.* TO 'ssbd06auth'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON ssbd06.* TO 'ssbd06mol'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON ssbd06.* TO 'ssbd06mok'@'%';